don't run the static_version_cache script by default
git-svn-id: https://svn.develooper.com/combust/trunk@649 516b4451-ceb8-0310-875f-b17149c99682

diff --git a/bin/run_httpd b/bin/run_httpd
--- a/bin/run_httpd
+++ b/bin/run_httpd
@@ -29,9 +29,9 @@ if test -e $CBROOTLOCAL/bin/httpd_setup -a -x $CBROOTLOCAL/bin/httpd_setup; then
    fi
 fi
 
-if ! $CBROOT/bin/deploy/static_version_cache; then
-  echo ERROR: bin/deploy/static_version_cache failed; exit
-fi
+#if ! $CBROOT/bin/deploy/static_version_cache; then
+#  echo ERROR: bin/deploy/static_version_cache failed; exit
+#fi
 
 # TODO: change this to check if the httpd is still running every second
 mkdir -p $WORK_PATH/htdocs && mkdir -p $WORK_PATH/ctpl && mkdir -p $LOG_PATH && \
